[2025-07-18 23:46:59] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-18 23:47:07] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:07] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:08] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:08] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:08] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:08] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:08] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:08] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:08] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:09] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:09] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:09] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:09] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:10] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:11] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:11] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:12] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:12] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:12] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:12] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:12] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:12] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:12] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:13] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:13] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:42] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:42] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:43] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:43] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-18 23:47:43] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 00:01:12] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 00:01:21] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:01:21] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:01:22] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:01:22] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:01:23] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:10:39] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:10:39] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:10:39] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:10:40] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:10:40] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: Antenna.__init__() got an unexpected keyword argument 'operational_status'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 87, in assign_antennas_to_activities
    compatible_antennas = self.ground_station_repository.get_compatible_antennas(activity.satellite_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in get_compatible_antennas
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/ground_station_repository_postgres.py", line 68, in <listcomp>
    return [Antenna(id=row[0], name=row[1], operational_status=row[2], is_active=row[3]) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Antenna.__init__() got an unexpected keyword argument 'operational_status'
[2025-07-20 00:11:31] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 00:11:39] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'Antenna' object is not subscriptable
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 93, in assign_antennas_to_activities
    antenna_id=antenna['id'],
               ~~~~~~~^^^^^^
TypeError: 'Antenna' object is not subscriptable
[2025-07-20 00:11:39] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'Antenna' object is not subscriptable
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 93, in assign_antennas_to_activities
    antenna_id=antenna['id'],
               ~~~~~~~^^^^^^
TypeError: 'Antenna' object is not subscriptable
[2025-07-20 00:11:39] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'Antenna' object is not subscriptable
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 93, in assign_antennas_to_activities
    antenna_id=antenna['id'],
               ~~~~~~~^^^^^^
TypeError: 'Antenna' object is not subscriptable
[2025-07-20 00:11:39] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'Antenna' object is not subscriptable
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 93, in assign_antennas_to_activities
    antenna_id=antenna['id'],
               ~~~~~~~^^^^^^
TypeError: 'Antenna' object is not subscriptable
[2025-07-20 00:11:40] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'Antenna' object is not subscriptable
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 93, in assign_antennas_to_activities
    antenna_id=antenna['id'],
               ~~~~~~~^^^^^^
TypeError: 'Antenna' object is not subscriptable
[2025-07-20 00:15:56] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 00:16:14] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 92, in assign_antennas_to_activities
    if self.pass_activity_repository.is_antenna_available(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 65, in is_antenna_available
    cur.execute("""
psycopg2.errors.UndefinedFunction: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2025-07-20 00:16:14] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 92, in assign_antennas_to_activities
    if self.pass_activity_repository.is_antenna_available(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 65, in is_antenna_available
    cur.execute("""
psycopg2.errors.UndefinedFunction: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2025-07-20 00:16:14] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 92, in assign_antennas_to_activities
    if self.pass_activity_repository.is_antenna_available(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 65, in is_antenna_available
    cur.execute("""
psycopg2.errors.UndefinedFunction: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2025-07-20 00:16:15] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 92, in assign_antennas_to_activities
    if self.pass_activity_repository.is_antenna_available(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 65, in is_antenna_available
    cur.execute("""
psycopg2.errors.UndefinedFunction: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2025-07-20 00:16:15] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 92, in assign_antennas_to_activities
    if self.pass_activity_repository.is_antenna_available(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 65, in is_antenna_available
    cur.execute("""
psycopg2.errors.UndefinedFunction: function tsrange(timestamp with time zone, timestamp with time zone) does not exist
LINE 6:                     AND tsrange(a.start_time, a.end_time) &&...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2025-07-20 00:28:41] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 00:29:15] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'PassActivity' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 99, in assign_antennas_to_activities
    activity_id=activity.id,
                ^^^^^^^^^^^
AttributeError: 'PassActivity' object has no attribute 'id'
[2025-07-20 00:29:16] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'PassActivity' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 99, in assign_antennas_to_activities
    activity_id=activity.id,
                ^^^^^^^^^^^
AttributeError: 'PassActivity' object has no attribute 'id'
[2025-07-20 00:29:16] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'PassActivity' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 99, in assign_antennas_to_activities
    activity_id=activity.id,
                ^^^^^^^^^^^
AttributeError: 'PassActivity' object has no attribute 'id'
[2025-07-20 00:29:16] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'PassActivity' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 99, in assign_antennas_to_activities
    activity_id=activity.id,
                ^^^^^^^^^^^
AttributeError: 'PassActivity' object has no attribute 'id'
[2025-07-20 00:29:16] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: 'PassActivity' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 99, in assign_antennas_to_activities
    activity_id=activity.id,
                ^^^^^^^^^^^
AttributeError: 'PassActivity' object has no attribute 'id'
[2025-07-20 00:54:23] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 00:54:48] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(1821eff5-38ed-4722-9daf-9f8e568f9fd0) is not present in table "activities".
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 98, in assign_antennas_to_activities
    self.pass_activity_repository.assign_antenna_to_activity(
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 80, in assign_antenna_to_activity
    cur.execute("""
psycopg2.errors.ForeignKeyViolation: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(1821eff5-38ed-4722-9daf-9f8e568f9fd0) is not present in table "activities".

[2025-07-20 00:54:48] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(83ee8c96-46dc-4e78-bf1b-d022e4017320) is not present in table "activities".
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 98, in assign_antennas_to_activities
    self.pass_activity_repository.assign_antenna_to_activity(
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 80, in assign_antenna_to_activity
    cur.execute("""
psycopg2.errors.ForeignKeyViolation: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(83ee8c96-46dc-4e78-bf1b-d022e4017320) is not present in table "activities".

[2025-07-20 00:54:49] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(f037efe6-2f93-43d1-893e-80e7d0cc13df) is not present in table "activities".
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 98, in assign_antennas_to_activities
    self.pass_activity_repository.assign_antenna_to_activity(
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 80, in assign_antenna_to_activity
    cur.execute("""
psycopg2.errors.ForeignKeyViolation: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(f037efe6-2f93-43d1-893e-80e7d0cc13df) is not present in table "activities".

[2025-07-20 00:54:49] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(94b068eb-2a6e-43ff-b03a-09ff0dcca604) is not present in table "activities".
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 98, in assign_antennas_to_activities
    self.pass_activity_repository.assign_antenna_to_activity(
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 80, in assign_antenna_to_activity
    cur.execute("""
psycopg2.errors.ForeignKeyViolation: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(94b068eb-2a6e-43ff-b03a-09ff0dcca604) is not present in table "activities".

[2025-07-20 00:54:49] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(9f4d00a7-ade1-4f70-b917-e879188404f6) is not present in table "activities".
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 44, in consume_tle_messages
    orchestrator.handle_tle_message(value)
  File "/app/application/orchestrator.py", line 80, in handle_tle_message
    self.assign_antennas_to_activities(valid_passes)
  File "/app/application/orchestrator.py", line 98, in assign_antennas_to_activities
    self.pass_activity_repository.assign_antenna_to_activity(
  File "/app/infrastructure/repositories/activity_repository_postgres.py", line 80, in assign_antenna_to_activity
    cur.execute("""
psycopg2.errors.ForeignKeyViolation: insert or update on table "activity_assignments" violates foreign key constraint "activity_assignments_activity_id_fkey"
DETAIL:  Key (activity_id)=(9f4d00a7-ade1-4f70-b917-e879188404f6) is not present in table "activities".

[2025-07-20 00:56:53] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 00:56:59] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 00:56:59] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 00:57:00] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 00:57:00] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 00:57:01] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 00:59:23] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 00:59:59] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:00:00] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:00:00] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:00:00] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:00:01] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:17:34] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:17:35] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:17:35] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:17:36] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:17:36] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:23:35] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 01:24:19] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:14] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-20 01:43:18] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:18] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:18] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:19] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:19] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:20] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:20] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:20] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:21] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-20 01:43:21] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
